scim:
  jwt:
    secret-name: scim/jwt-signing-key
    issuer: scim-service
  ses:
    from-address: noreply@scim.local
  base-url: http://localhost:8080

aws:
  secretsmanager:
    endpoint: http://localhost:4566
  ses:
    endpoint: http://localhost:4566
  region: us-east-1

